EquityCalculatorMVC/Models/BaseEntity.cs
namespace EquityCalculatorMVC.Models;

public class BaseEntity
{
    public int Id { get; set; }
}

EquityCalculatorMVC/Models/CombinedEntity.cs
namespace EquityCalculatorMVC.Models;

public class CombinedEntity
{
    public EquityCalculator EquityCalculator { get; set; }
    public List<EquitySchedule> EquitySchedule { get; set; }
}

EquityCalculatorMVC/Models/EquityCalculator.cs
namespace EquityCalculatorMVC.Models;

public class EquityCalculator
{
    public decimal SellingPrice { get; set; }
    public DateTime ReservationDate { get; set; }
    public int EquityTerm { get; set; }
}

EquityCalculatorMVC/Models/EquitySchedule.cs
namespace EquityCalculatorMVC.Models;

public class EquitySchedule : BaseEntity
{
    public decimal Balance { get; set; }
    public DateTime DueDate { get; set; }
    public int Term { get; set; }
    public List<PaymentInfo> PaymentInfo { get; set; }
}

EquityCalculatorMVC/Models/ErrorViewModel.cs
namespace EquityCalculatorMVC.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

EquityCalculatorMVC/Models/PaymentInfo.cs
namespace EquityCalculatorMVC.Models;

public class PaymentInfo : BaseEntity
{
    public decimal Amount { get; set; }
    public decimal Interest { get; set; }
    public decimal Insurance { get; set; }
    public decimal Total { get; set; }
}

EquityCalculatorMVC/Controllers/EquityCalculatorController.cs
using EquityCalculatorMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace EquityCalculatorMVC.Controllers;

public class EquityCalculatorController : Controller
{
    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult CalculateEquity()
    {
        return View();
    }


    [HttpPost("calculator")]
    public async Task<ActionResult<IReadOnlyList<EquitySchedule>>> CalculateEquity(EquityCalculator equityCalculator)
    {
        var equitySchedule = new List<EquitySchedule>();
        decimal balance = equityCalculator.SellingPrice;
        decimal amount = equityCalculator.SellingPrice / equityCalculator.EquityTerm;
        decimal interest = balance * (decimal)0.05;
        decimal insurance = amount * (decimal)0.01;

        for (int i = 0; i <= equityCalculator.EquityTerm - 1; i++)
        {
            var equity = new EquitySchedule
            {
                Id = i + 1,
                Balance = balance - amount,
                DueDate = equityCalculator.ReservationDate.AddMonths(i + 1),
                Term = i + 1,
                PaymentInfo = new List<PaymentInfo>
                {
                    new PaymentInfo
                    {
                        Id = i + 1,
                        Amount = Convert.ToDecimal(amount),
                        Interest = Convert.ToDecimal(interest),
                        Insurance = insurance,
                        Total = GetTotal()
                    }
                }
            };
            equitySchedule.Add(equity);
            balance -= amount;
        }
        decimal GetTotal()
        {
            return amount + interest + insurance;
        }

        return View("CalculateEquity", equitySchedule);
    }
}

EquityCalculatorMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EquityCalculatorMVC.Models;

namespace EquityCalculatorMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }
    
    public IActionResult Index()
    {
        return View();
    }

    

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

EquityCalculatorMVC/Views/EquityCalculator/CalculateEquity.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
@model List<EquitySchedule>


<table class="table">
    <thead>
    <td>Balance</td>
    <td>Due Date</td>
    <td>Term</td>
    <td>Payment Info</td>
    </thead>
    <tbody>
    @foreach (var list in @Model.ToList())
    {
        <tr>
            <td>@list.Balance</td>
            <td>@list.DueDate.Date</td>
            <td>@list.Term</td>
            <td>
                <ul class="list-unstyled">
                    <li>
                        <strong>Amount: </strong>@list.PaymentInfo[0].Amount
                    </li>
                    <li>
                        <strong>Interest: </strong> @list.PaymentInfo[0].Interest
                    </li>
                    <li>
                        <strong>Insurance: </strong> @list.PaymentInfo[0].Insurance
                    </li>
                    <li>
                        <strong>Total: </strong> @list.PaymentInfo[0].Total
                    </li>
                </ul>
            </td>
        </tr>
    }

    </tbody>
</table>

EquityCalculatorMVC/Views/EquityCalculator/Index.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
@model EquityCalculator

<div class="row justify-content-center">
    <div class="col-5">
        <form method="post" asp-action="CalculateEquity">
            <div class="card">
                <div class="card-header">Calculator</div>
                <div class="card-body">
                    <div class="form-group">
                        <label class="">Selling Price</label>
                        <input asp-for="SellingPrice" type="text" class="form-control" placeholder="Selling Price">
                    </div>
                    <div class="form-group">
                        <label class="">Reservation Date</label>
                        <input asp-for="ReservationDate" type="date" class="form-control" placeholder="Reservation Date">
                    </div>
                    <div class="form-group mb-4">
                        <label class="">Equity Term</label>
                        <input asp-for="EquityTerm" type="number" class="form-control" placeholder="Equity Term">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Compute</button>
                    </div>
                    
                </div>
            </div>
        </form>
    </div>
</div>

EquityCalculatorMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row justify-content-center">
    <h4>Welcome!</h4>
    <a class="btn btn-lg btn-primary" asp-controller="EquityCalculator" asp-action="Index">Proceed</a>
    
</div>

EquityCalculatorMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - EquityCalculatorMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/EquityCalculatorMVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EquityCalculatorMVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - EquityCalculatorMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>